### ISSUE TITLE
What other functionality do you have planned?

### ISSUE THREAD

**Issue by russomi** [loong/google-cloud-function-boiler#1]
Hi @mindworker ... just wanted to say "thanks" for putting this together.  

Do you have any plans to add local unit testing support?  I was thinking it could help one mock other types of triggers such as storage and topic?

👍

**Comment by loong** [comment]
Hi @russomi! Thanks. I I mainly code in go, so my node skills are very crude. 

I actually created a better dev server the last few days, the current one doesn't properly support requests (e.g. no body for `POST`). I will add it if there is interest.

Mocking other types of triggers is a good idea. I will keep it in mind. For unit tests, how do you suggest to include it into this boiler?
